import mongoose from "mongoose";
import connectDB from "../lib/mongodb";
import Property from "../models/Property";

const SEED_DATA = [
  // ── Nashik ──────────────────────────────────────────────────────────────────
  {
    surveyNumber: "MH-NK-2024-0001",
    propertyName: "Satpur MIDC Industrial Unit A",
    city: "Nashik",
    locality: "Satpur MIDC",
    location: { type: "Point", coordinates: [73.7398, 19.9975] },
    reverseGeoAddress: "Satpur MIDC, Nashik, Maharashtra",
    areaSqFt: 12000,
    buildingAge: 8,
    numberOfFloors: 1,
    constructionQuality: 4,
    zoningType: "Industrial",
    ownershipType: "Freehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 24000000,
      valuationRangeLow: 21000000,
      valuationRangeHigh: 27000000,
      monthlyRentalINR: 96000,
      annualYieldPercent: 4.8,
      investmentGrade: "B+",
      confidenceScore: 82,
      aiInsights: [
        "Well-maintained single-floor structure with quality RCC construction",
        "Located within established Satpur MIDC, ensuring steady industrial demand",
        "8-year-old building in excellent condition — minimal maintenance costs expected",
        "Good road connectivity to NH-3 highway for logistics operations",
        "Proximity to Nashik railway freight terminal adds to logistics value",
      ],
      riskFlags: [],
    },
  },
  {
    surveyNumber: "MH-NK-2024-0002",
    propertyName: "Ambad MIDC Warehouse Complex",
    city: "Nashik",
    locality: "Ambad MIDC",
    location: { type: "Point", coordinates: [73.8107, 20.0059] },
    reverseGeoAddress: "Ambad MIDC, Nashik, Maharashtra",
    areaSqFt: 35000,
    buildingAge: 15,
    numberOfFloors: 2,
    constructionQuality: 3,
    zoningType: "Warehousing",
    ownershipType: "Leasehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 52500000,
      valuationRangeLow: 46000000,
      valuationRangeHigh: 59000000,
      monthlyRentalINR: 175000,
      annualYieldPercent: 4.0,
      investmentGrade: "B",
      confidenceScore: 74,
      aiInsights: [
        "Large warehousing facility with 35,000 sqft — ideal for e-commerce/3PL operators",
        "Ambad MIDC is Nashik's premier industrial zone with high occupancy rates",
        "15-year-old building shows moderate wear — structural assessment recommended",
        "Leasehold status limits resale potential; verify lease remaining tenure",
        "Two-floor layout may require goods lift — check if installed",
      ],
      riskFlags: ["Leasehold property — verify remaining lease years before purchase", "Building age warrants structural audit"],
    },
  },
  {
    surveyNumber: "MH-NK-2024-0003",
    propertyName: "Sinnar Industrial Plot — Phase II",
    city: "Nashik",
    locality: "Sinnar",
    location: { type: "Point", coordinates: [74.0023, 19.8473] },
    reverseGeoAddress: "Sinnar Industrial Area, Nashik, Maharashtra",
    areaSqFt: 8500,
    buildingAge: 3,
    numberOfFloors: 1,
    constructionQuality: 5,
    zoningType: "Industrial",
    ownershipType: "Freehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 18700000,
      valuationRangeLow: 16500000,
      valuationRangeHigh: 21000000,
      monthlyRentalINR: 68000,
      annualYieldPercent: 4.4,
      investmentGrade: "A",
      confidenceScore: 91,
      aiInsights: [
        "Brand new 3-year-old construction with premium quality finish",
        "Sinnar is an emerging industrial hub with attractive land prices",
        "Excellent construction quality rated 5/5 — built to modern industrial standards",
        "Close to Delhi-Mumbai Industrial Corridor (DMIC) node at Sinnar",
        "Strong long-term appreciation potential given DMIC proximity",
      ],
      riskFlags: [],
    },
  },
  {
    surveyNumber: "MH-NK-2023-0004",
    propertyName: "Igatpuri Cold Storage Facility",
    city: "Nashik",
    locality: "Igatpuri",
    location: { type: "Point", coordinates: [73.5586, 19.6942] },
    reverseGeoAddress: "Igatpuri, Nashik, Maharashtra",
    areaSqFt: 22000,
    buildingAge: 22,
    numberOfFloors: 1,
    constructionQuality: 2,
    zoningType: "Commercial",
    ownershipType: "Freehold",
    status: "flagged",
    valuation: {
      estimatedValueINR: 28600000,
      valuationRangeLow: 24000000,
      valuationRangeHigh: 33000000,
      monthlyRentalINR: 88000,
      annualYieldPercent: 3.7,
      investmentGrade: "C",
      confidenceScore: 58,
      aiInsights: [
        "Cold storage facility strategically located on Mumbai-Agra highway",
        "Igatpuri's agro-processing corridor makes this property contextually valuable",
        "22-year-old structure with visibly aging infrastructure",
        "Significant capex required to bring facility up to modern standards",
        "Location on key highway route supports logistics use cases",
      ],
      riskFlags: [
        "Building age of 22 years — major renovation likely required",
        "Construction quality rated 2/5 — structural inspection mandatory",
        "Flagged for re-assessment pending physical inspection",
      ],
    },
  },
  {
    surveyNumber: "MH-NK-2024-0005",
    propertyName: "Nashik Road Mixed-Use Industrial",
    city: "Nashik",
    locality: "Nashik Road",
    location: { type: "Point", coordinates: [73.9253, 19.9603] },
    reverseGeoAddress: "Nashik Road, Nashik, Maharashtra",
    areaSqFt: 6200,
    buildingAge: 11,
    numberOfFloors: 3,
    constructionQuality: 4,
    zoningType: "Mixed",
    ownershipType: "Freehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 16740000,
      valuationRangeLow: 14500000,
      valuationRangeHigh: 19000000,
      monthlyRentalINR: 58000,
      annualYieldPercent: 4.2,
      investmentGrade: "B+",
      confidenceScore: 79,
      aiInsights: [
        "Three-floor mixed-use structure near Nashik Road railway station",
        "Mixed zoning allows flexible tenant mix — retail + office + light industrial",
        "Well-connected location with high footfall from Nashik Road commuters",
        "Good construction quality with standard commercial-grade finish",
        "Rental demand strong from SMEs and trading businesses in the corridor",
      ],
      riskFlags: [],
    },
  },

  // ── Mumbai ───────────────────────────────────────────────────────────────────
  {
    surveyNumber: "MH-MU-2024-0001",
    propertyName: "Bhiwandi Logistics Hub Unit 7",
    city: "Mumbai",
    locality: "Bhiwandi",
    location: { type: "Point", coordinates: [73.0534, 19.2961] },
    reverseGeoAddress: "Bhiwandi, Thane, Maharashtra",
    areaSqFt: 48000,
    buildingAge: 6,
    numberOfFloors: 2,
    constructionQuality: 4,
    zoningType: "Warehousing",
    ownershipType: "Leasehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 216000000,
      valuationRangeLow: 190000000,
      valuationRangeHigh: 240000000,
      monthlyRentalINR: 720000,
      annualYieldPercent: 4.0,
      investmentGrade: "A",
      confidenceScore: 88,
      aiInsights: [
        "Bhiwandi is India's largest warehousing hub — extremely high demand",
        "48,000 sqft Grade A warehouse with 12m ceiling height",
        "Adjacent to NH-61 — perfect for last-mile delivery operations",
        "Strong tenant base from e-commerce, FMCG, and 3PL companies",
        "6-year-old building in excellent operational condition",
      ],
      riskFlags: ["Leasehold — verify lease tenor before committing capital"],
    },
  },
  {
    surveyNumber: "MH-MU-2024-0002",
    propertyName: "Kurla Industrial Estate Block C",
    city: "Mumbai",
    locality: "Kurla",
    location: { type: "Point", coordinates: [72.8836, 19.0726] },
    reverseGeoAddress: "Kurla Industrial Estate, Mumbai, Maharashtra",
    areaSqFt: 9500,
    buildingAge: 35,
    numberOfFloors: 4,
    constructionQuality: 2,
    zoningType: "Industrial",
    ownershipType: "Freehold",
    status: "pending",
    valuation: {
      estimatedValueINR: 71250000,
      valuationRangeLow: 62000000,
      valuationRangeHigh: 82000000,
      monthlyRentalINR: 190000,
      annualYieldPercent: 3.2,
      investmentGrade: "C",
      confidenceScore: 62,
      aiInsights: [
        "Prime Kurla location offers very high land value despite aging structure",
        "Potential redevelopment play — land value exceeds building value",
        "35-year-old structure requires significant capital investment",
        "Central Mumbai location with excellent connectivity (road + rail)",
        "Current rental yield is below market — indicates upside after renovation",
      ],
      riskFlags: [
        "Structure is 35 years old — comprehensive structural audit required",
        "Low construction quality (2/5) — significant renovation budget needed",
      ],
    },
  },
  {
    surveyNumber: "MH-MU-2023-0003",
    propertyName: "Thane Industrial Park — Tower 2",
    city: "Mumbai",
    locality: "Thane Industrial",
    location: { type: "Point", coordinates: [72.9777, 19.1832] },
    reverseGeoAddress: "Thane Industrial Area, Thane, Maharashtra",
    areaSqFt: 18500,
    buildingAge: 0,
    numberOfFloors: 5,
    constructionQuality: 5,
    zoningType: "Commercial",
    ownershipType: "Freehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 148000000,
      valuationRangeLow: 135000000,
      valuationRangeHigh: 162000000,
      monthlyRentalINR: 462500,
      annualYieldPercent: 3.75,
      investmentGrade: "A",
      confidenceScore: 94,
      aiInsights: [
        "New construction (0 years) — no depreciation and zero deferred maintenance",
        "5-star construction quality with modern commercial specifications",
        "Thane is fast emerging as MMR's preferred commercial-industrial destination",
        "5-floor structure suitable for large corporate tenants",
        "Strong capital appreciation expected over next 5 years in Thane corridor",
      ],
      riskFlags: [],
    },
  },
  {
    surveyNumber: "MH-MU-2024-0004",
    propertyName: "Navi Mumbai Turbhe Facility",
    city: "Mumbai",
    locality: "Turbhe MIDC",
    location: { type: "Point", coordinates: [73.0297, 19.0760] },
    reverseGeoAddress: "Turbhe MIDC, Navi Mumbai, Maharashtra",
    areaSqFt: 26000,
    buildingAge: 18,
    numberOfFloors: 2,
    constructionQuality: 3,
    zoningType: "Industrial",
    ownershipType: "Leasehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 117000000,
      valuationRangeLow: 102000000,
      valuationRangeHigh: 132000000,
      monthlyRentalINR: 390000,
      annualYieldPercent: 4.0,
      investmentGrade: "B",
      confidenceScore: 76,
      aiInsights: [
        "Turbhe MIDC is a mature industrial zone with stable occupancy",
        "26,000 sqft floor plate suitable for mid-size manufacturing operations",
        "18-year building with functional but dated infrastructure",
        "JNPT proximity (15km) adds supply chain logistics value",
        "Consider mechanical and electrical upgrades to improve rental yield",
      ],
      riskFlags: ["Leasehold — lease renewal terms require verification"],
    },
  },
  {
    surveyNumber: "MH-MU-2024-0005",
    propertyName: "Kalyan Industrial Shed Block 11",
    city: "Mumbai",
    locality: "Kalyan",
    location: { type: "Point", coordinates: [73.1645, 19.2437] },
    reverseGeoAddress: "Kalyan Industrial Area, Thane, Maharashtra",
    areaSqFt: 7800,
    buildingAge: 28,
    numberOfFloors: 1,
    constructionQuality: 2,
    zoningType: "Industrial",
    ownershipType: "Freehold",
    status: "pending",
    valuation: {
      estimatedValueINR: 31200000,
      valuationRangeLow: 26000000,
      valuationRangeHigh: 36000000,
      monthlyRentalINR: 78000,
      annualYieldPercent: 3.0,
      investmentGrade: "D",
      confidenceScore: 55,
      aiInsights: [
        "Kalyan fringe location with lower land values compared to central MMR",
        "Old industrial shed with obsolete design for modern operations",
        "Freehold ownership is the main value anchor for this property",
        "Best suited for buyers willing to demolish and reconstruct",
        "Rental demand limited to small-scale storage and light industry",
      ],
      riskFlags: [
        "28-year-old structure — near end of usable life",
        "Construction quality 2/5 — not suitable for most modern tenants",
        "Low rental yield of 3% below market benchmark",
      ],
    },
  },

  // ── Pune ──────────────────────────────────────────────────────────────────
  {
    surveyNumber: "MH-PN-2024-0001",
    propertyName: "Pimpri-Chinchwad MIDC Unit 34",
    city: "Pune",
    locality: "Pimpri-Chinchwad MIDC",
    location: { type: "Point", coordinates: [73.7983, 18.6298] },
    reverseGeoAddress: "Pimpri-Chinchwad MIDC, Pune, Maharashtra",
    areaSqFt: 20000,
    buildingAge: 12,
    numberOfFloors: 2,
    constructionQuality: 4,
    zoningType: "Industrial",
    ownershipType: "Freehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 78000000,
      valuationRangeLow: 69000000,
      valuationRangeHigh: 88000000,
      monthlyRentalINR: 260000,
      annualYieldPercent: 4.0,
      investmentGrade: "A",
      confidenceScore: 87,
      aiInsights: [
        "PCMC MIDC is Pune's flagship industrial zone — highest demand in region",
        "Premium auto-ancillary and engineering manufacturing location",
        "20,000 sqft dual-floor layout ideal for mid-scale manufacturing",
        "12-year-old quality construction — well within prime operational life",
        "PCMC metro connectivity imminent — will drive significant value appreciation",
      ],
      riskFlags: [],
    },
  },
  {
    surveyNumber: "MH-PN-2024-0002",
    propertyName: "Chakan Auto Ancillary Shed",
    city: "Pune",
    locality: "Chakan",
    location: { type: "Point", coordinates: [73.8567, 18.7583] },
    reverseGeoAddress: "Chakan Industrial Area, Pune, Maharashtra",
    areaSqFt: 42000,
    buildingAge: 7,
    numberOfFloors: 1,
    constructionQuality: 5,
    zoningType: "Industrial",
    ownershipType: "Freehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 168000000,
      valuationRangeLow: 150000000,
      valuationRangeHigh: 188000000,
      monthlyRentalINR: 546000,
      annualYieldPercent: 3.9,
      investmentGrade: "A",
      confidenceScore: 92,
      aiInsights: [
        "Chakan is the automotive capital of India — Volkswagen, Mahindra, Tata all nearby",
        "42,000 sqft premium single-floor shed with 14m eaves height",
        "Excellent construction quality purpose-built for auto manufacturing",
        "7-year-old structure in prime operational condition",
        "Long-term tenant demand virtually guaranteed given OEM ecosystem",
      ],
      riskFlags: [],
    },
  },
  {
    surveyNumber: "MH-PN-2023-0003",
    propertyName: "Talegaon Dabhade Logistics Center",
    city: "Pune",
    locality: "Talegaon",
    location: { type: "Point", coordinates: [73.6780, 18.7283] },
    reverseGeoAddress: "Talegaon Dabhade, Pune, Maharashtra",
    areaSqFt: 30000,
    buildingAge: 4,
    numberOfFloors: 1,
    constructionQuality: 4,
    zoningType: "Warehousing",
    ownershipType: "Freehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 105000000,
      valuationRangeLow: 94000000,
      valuationRangeHigh: 118000000,
      monthlyRentalINR: 315000,
      annualYieldPercent: 3.6,
      investmentGrade: "B+",
      confidenceScore: 85,
      aiInsights: [
        "Talegaon is on the Pune-Mumbai Expressway — prime logistics location",
        "30,000 sqft modern warehouse with dock levelers and fire suppression",
        "4-year-old facility in pristine condition",
        "Growing catchment for Pune's western industrial expansion",
        "Expressway access reduces transit time significantly for national freight",
      ],
      riskFlags: [],
    },
  },
  {
    surveyNumber: "MH-PN-2024-0004",
    propertyName: "Hadapsar IT-Industrial Complex",
    city: "Pune",
    locality: "Hadapsar",
    location: { type: "Point", coordinates: [73.9355, 18.5089] },
    reverseGeoAddress: "Hadapsar, Pune, Maharashtra",
    areaSqFt: 15000,
    buildingAge: 16,
    numberOfFloors: 3,
    constructionQuality: 3,
    zoningType: "Mixed",
    ownershipType: "Freehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 82500000,
      valuationRangeLow: 74000000,
      valuationRangeHigh: 93000000,
      monthlyRentalINR: 240000,
      annualYieldPercent: 3.5,
      investmentGrade: "B",
      confidenceScore: 72,
      aiInsights: [
        "Hadapsar is Pune's IT-industrial convergence zone",
        "Mixed-use zoning captures both IT office and light industrial demand",
        "3-floor structure well-suited for multi-tenant setup",
        "16 years old — cosmetic upgrades recommended for modern tenants",
        "Adjacency to Magarpatta and EON IT Park drives tenant spillover demand",
      ],
      riskFlags: ["Building age warrants plumbing and electrical system review"],
    },
  },
  {
    surveyNumber: "MH-PN-2024-0005",
    propertyName: "Ranjangaon SEZ Industrial Plot",
    city: "Pune",
    locality: "Ranjangaon",
    location: { type: "Point", coordinates: [74.1833, 18.7142] },
    reverseGeoAddress: "Ranjangaon MIDC, Pune, Maharashtra",
    areaSqFt: 55000,
    buildingAge: 9,
    numberOfFloors: 1,
    constructionQuality: 4,
    zoningType: "Industrial",
    ownershipType: "Leasehold",
    status: "verified",
    valuation: {
      estimatedValueINR: 192500000,
      valuationRangeLow: 172000000,
      valuationRangeHigh: 215000000,
      monthlyRentalINR: 577500,
      annualYieldPercent: 3.6,
      investmentGrade: "B+",
      confidenceScore: 80,
      aiInsights: [
        "Ranjangaon MIDC houses Fiat, General Electric, and Schneider facilities",
        "55,000 sqft large-format shed suitable for Tier-1 auto suppliers",
        "SEZ benefits available — significant tax advantages for eligible tenants",
        "9-year-old premium construction in excellent operational condition",
        "Pune-Ahmednagar highway connectivity makes national logistics straightforward",
      ],
      riskFlags: ["Leasehold status — review MIDC lease remaining period"],
    },
  },
];

async function seed() {
  await connectDB();

  console.log("⚠️  WARNING: Clearing all existing properties from the database...");
  await Property.deleteMany({});
  console.log("✅ Collection cleared");

  const docs = SEED_DATA.map((d) => ({
    ...d,
    surveyNumber: d.surveyNumber.toUpperCase(),
  }));

  await Property.insertMany(docs);
  console.log(`✅ Seeded ${docs.length} properties successfully`);

  await mongoose.disconnect();
  console.log("✅ Disconnected from MongoDB");
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});